// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
interface Env {
    /**
     * without trailing slash
     */
    proxy_baseurl: string
    proxy_host?: string
    request: {
        delete_headers: string[]
        add_headers: Record<string, string>
    },
    response: {
        delete_headers: string[]
        add_headers: Record<string, string>
    },
    cors: {
        hijack_options?: boolean
        advanced_allow_origins?: false | string[]
        options_headers: Record<string, string>
    }
}
